### ISSUE TITLE
Doesn't work when using a custom stack name. 

### ISSUE THREAD

**Issue by all9lives** [drexler/serverless-cloudformation-resource-counter#6]
Great plugin and has been useful. We've recently hit up against the limit and so have broken up our resources into multiple stacks. 

The plugin only seems to work if you use the default sls stack naming convention, and doesn't account for setting `provider.stackName` as outlined in the [serverless.yml Reference](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/)

```
provider:
  stackName: custom-stack-name
```

Would it be possible to allow for custom stack names now that serverless supports it?

**Comment by drexler** [comment]
@all9lives thanks for reporting this issue. I will be looking into it.

**Comment by drexler** [comment]
@all9lives, an updated version of the plugin has been published to support this change.
